server:
  port: 8090
spring:
  profiles:
    active: ${profile}

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create
  database-platform: org.hibernate.dialect.H2Dialect

  output:
    ansi:
      enabled: ALWAYS

#springdoc swagger
springdoc:
  api-docs:
    enabled: true #false 지정 시 외부 노출 X
  swagger-ui:
    enabled: true