server:
  port: 8090
spring:
  profiles:
    active: oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/zupzup
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: ALWAYS