server:
  port: 8090
spring:
  profiles:
    active: ${profile}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  output:
    ansi:
      enabled: ALWAYS

#springdoc swagger
springdoc:
  api-docs:
    enabled: true #false 지정 시 외부 노출 X
  swagger-ui:
    enabled: true