spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/zupzup
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      secret-key: qkdzKsrUli2EVVv+shtXzuqsRhn+oq3AmZ9x/2WF
      access-key: AKIAXNUQH7X3T4JMMLM5
    s3:
      bucket: zupzupbucket