name: ZupZup CI

on:
  pull_request:
    branches: [ "main" ] # main 브랜치에 대한 PR에 대해서만 작동하도록 설정

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive' # 서브모듈을 체크아웃하도록 설정
        token: ${{ secrets.ACTIONS_TOKEN }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew # 현재 작업 디렉토리를 사용하는 것이 더 일반적인 접근법
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
