server:
  port: 8080
spring:
  profiles:
    active: ${profile}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create
  database-platform: org.hibernate.dialect.H2Dialect

  output:
    ansi:
      enabled: ALWAYS

logging:  # 로그 레벨 설정
  level:
    org.hibernate.SQL: debug  # hibernate 가 남기는 모든 로그가 debug모드로 설정, jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      secret-key:
      access-key:
    s3:
      bucket: zupzupbucket

#springdoc swagger
springdoc:
  api-docs:
    enabled: true #false 지정 시 외부 노출 X
  swagger-ui:
    enabled: true