server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/zupzup
    username: sa
    password:
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: ALWAYS

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      secret-key:
      access-key:
    s3:
      bucket: zupzupbucket